# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomchat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchat',
            name='participants',
        ),
    ]
