# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomchat', '0003_auto_20180114_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchat',
            name='admin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_rooms', to='userprofile.UserProfile'),
        ),
    ]
